//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp25
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.RepairReport = new HashSet<RepairReport>();
        }
    
        public int RequestID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string ProblemDescription { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> EquipmentID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> TechnicianID { get; set; }
        public Nullable<int> FaultTypeID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual FaultType FaultType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairReport> RepairReport { get; set; }
        public virtual Status Status { get; set; }
        public virtual Technician Technician { get; set; }
    }
}
